import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { appUser, council } from './platform.js';
import {
  caseKindEnum,
  caseStateEnum,
  closureReasonEnum,
  contactChannelEnum,
  contactDirectionEnum,
  dateSourceEnum,
  intakeSourceEnum,
  milestoneEnum,
  noticeStateEnum,
  partyKindEnum,
  partyRoleEnum,
  serviceModeEnum,
  waitingOnEnum,
} from './enums.js';

/**
 * The case and everything hanging off it.
 *
 * `case_file` is the canonical name (ADR-0001). One table carries both patient complaints
 * and ethical-violation notices; the difference is `case_kind` plus configuration, not a
 * second code path.
 */

/**
 * The dentist register. Populated by Excel import in Phase 5; until then the officer types
 * respondent details per case and this table stays thin. Upsert-never-delete: a dentist who
 * disappears from an import is marked `lapsed`, not removed, because cases reference them.
 */
export const registeredDentist = pgTable(
  'registered_dentist',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    registrationNo: text('registration_no').notNull(),
    fullName: text('full_name').notNull(),
    qualification: text('qualification'),
    clinicName: text('clinic_name'),
    addressLines: jsonb('address_lines').$type<string[]>(),
    email: text('email'),
    mobile: text('mobile'),
    status: text('status').notNull().default('active'), // active | lapsed | suspended
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('registered_dentist_uq').on(t.councilId, t.registrationNo),
    index('registered_dentist_name_ix').on(t.councilId, t.fullName),
  ],
);

/** A person or organisation. Reused across cases so a respondent accrues a history. */
export const party = pgTable(
  'party',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    kind: partyKindEnum('kind').notNull().default('person'),
    fullName: text('full_name').notNull(),
    mobile: text('mobile'),
    /** Digits only, for matching a caller against an existing party. */
    mobileNormalised: text('mobile_normalised'),
    email: text('email'),
    addressLines: jsonb('address_lines').$type<string[]>(),
    ageYears: integer('age_years'),
    sex: text('sex'),
    /** Linked once the respondent is identified in the register. */
    registeredDentistId: uuid('registered_dentist_id').references(() => registeredDentist.id, {
      onDelete: 'set null',
    }),
    /** Informants on ethics notices may be confidential — never printed on a notice. */
    isConfidential: boolean('is_confidential').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('party_council_name_ix').on(t.councilId, t.fullName),
    index('party_mobile_ix').on(t.councilId, t.mobileNormalised),
  ],
);

export const caseFile = pgTable(
  'case_file',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),

    caseKind: caseKindEnum('case_kind').notNull().default('patient_complaint'),
    /** KSDC/COMP/2026-27/0042 — generated by us. */
    caseNumber: text('case_number').notNull(),
    fiscalYear: text('fiscal_year').notNull(), // '2026-27'
    /**
     * The register serial. Seeded from the physical book for backlog cases and continued
     * from the highest — renumbering a legal register is worse than a gap.
     */
    registerSlNo: integer('register_sl_no').notNull(),

    state: caseStateEnum('state').notNull().default('intake_received'),

    /**
     * GENERATED ALWAYS ... STORED — derived from `state` by Postgres, never written by the
     * application. A stored column maintained by a transition table drifts within months,
     * and a dashboard that looks authoritative and is wrong is worse than the paper book.
     *
     * Keep this expression in step with WAITING_ON_BY_STATE in @ksdc/contracts; a test
     * asserts the two agree for every state.
     */
    // Each branch is cast individually. Casting the CASE *result* to the enum fails with
    // "generation expression is not immutable": enum_in is STABLE (provolatile 's'), so an
    // outer cast is a runtime call. Per-branch literals are constant-folded at parse time.
    waitingOn: waitingOnEnum('waiting_on').generatedAlwaysAs(
      sql`(CASE state
            WHEN 'awaiting_complainant_documents'::case_state THEN 'complainant'::waiting_on
            WHEN 'awaiting_respondent_reply'::case_state      THEN 'respondent'::waiting_on
            WHEN 'awaiting_expert_report'::case_state         THEN 'expert_body'::waiting_on
            WHEN 'closed'::case_state                         THEN 'nobody'::waiting_on
            ELSE 'council_officer'::waiting_on
          END)`,
    ),
    /** When the current wait began. "Days waiting" on the register is now() minus this. */
    waitingSince: timestamp('waiting_since', { withTimezone: true }).notNull().defaultNow(),

    /** Sub judice, a party indisposed, awaiting an external authority. Suppresses deadlines. */
    onHold: boolean('on_hold').notNull().default(false),
    holdReason: text('hold_reason'),
    heldSince: timestamp('held_since', { withTimezone: true }),

    intakeSource: intakeSourceEnum('intake_source').notNull().default('direct_email'),
    /** A DCI/NDC or police reference, and any reply-by date they imposed. */
    externalRefNo: text('external_ref_no'),
    externalAuthorityName: text('external_authority_name'),
    externalDueAt: date('external_due_at'),

    summary: text('summary').notNull().default(''),
    remarks: text('remarks'),

    /** Every downstream deadline runs from here, not from receipt. */
    documentsCompleteAt: timestamp('documents_complete_at', { withTimezone: true }),

    closedAt: timestamp('closed_at', { withTimezone: true }),
    closureReason: closureReasonEnum('closure_reason'),
    closureNote: text('closure_note'),

    /** Entered from the paper book rather than recorded live. Footnoted in every export. */
    isBackfilled: boolean('is_backfilled').notNull().default(false),
    legacyRegisterRef: text('legacy_register_ref'),

    ownerUserId: uuid('owner_user_id').references(() => appUser.id, { onDelete: 'set null' }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid('created_by').references(() => appUser.id, { onDelete: 'set null' }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),

    /** No hard deletes anywhere. The app role has no DELETE grant. */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    deletedBy: uuid('deleted_by').references(() => appUser.id, { onDelete: 'set null' }),
    deletionReason: text('deletion_reason'),
  },
  (t) => [
    uniqueIndex('case_file_number_uq').on(t.councilId, t.caseNumber),
    uniqueIndex('case_file_serial_uq').on(t.councilId, t.fiscalYear, t.registerSlNo),
    index('case_file_queue_ix').on(t.councilId, t.state, t.waitingSince),
    index('case_file_waiting_ix').on(t.councilId, t.waitingOn, t.waitingSince),
    check(
      'case_file_closed_needs_reason',
      sql`(state <> 'closed') OR (closure_reason IS NOT NULL AND closed_at IS NOT NULL)`,
    ),
    check('case_file_hold_needs_reason', sql`(on_hold = false) OR (hold_reason IS NOT NULL)`),
  ],
);

export const casePartyTable = pgTable(
  'case_party',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    partyId: uuid('party_id')
      .notNull()
      .references(() => party.id, { onDelete: 'restrict' }),
    role: partyRoleEnum('role').notNull(),
    /** Complainant and patient default to the same person but are stored separately. */
    isPrimary: boolean('is_primary').notNull().default(false),
    note: text('note'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('case_party_uq').on(t.caseFileId, t.partyId, t.role),
    index('case_party_case_ix').on(t.councilId, t.caseFileId),
  ],
);

/**
 * A respondent's own state, independent of the case. One complaint may name several
 * dentists and an establishment; each gets its own notice ladder and its own outcome.
 */
export const caseRespondent = pgTable(
  'case_respondent',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    casePartyId: uuid('case_party_id')
      .notNull()
      .references(() => casePartyTable.id, { onDelete: 'restrict' }),

    noticeState: noticeStateEnum('notice_state').notNull().default('not_issued'),
    /**
     * Increments ONLY when the officer confirms a despatch. No timer touches this.
     * A timer-driven count would become the legal basis for an ex parte finding against
     * a named dentist, on a system whose premise is that things get forgotten.
     */
    noticeCount: integer('notice_count').notNull().default(0),
    replyDueAt: date('reply_due_at'),
    firstReplyAt: timestamp('first_reply_at', { withTimezone: true }),

    /** Computed from despatched notices with proof of service — never from a reminder. */
    exParteEligible: boolean('ex_parte_eligible').notNull().default(false),
    exParteAt: timestamp('ex_parte_at', { withTimezone: true }),
    exParteReason: text('ex_parte_reason'),

    droppedAt: timestamp('dropped_at', { withTimezone: true }),
    droppedReason: text('dropped_reason'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('case_respondent_uq').on(t.caseFileId, t.casePartyId),
    index('case_respondent_case_ix').on(t.councilId, t.caseFileId, t.noticeState),
    check(
      'case_respondent_ex_parte_needs_reason',
      sql`(ex_parte_at IS NULL) OR (ex_parte_reason IS NOT NULL)`,
    ),
    check('case_respondent_drop_needs_reason', sql`(dropped_at IS NULL) OR (dropped_reason IS NOT NULL)`),
  ],
);

export const respondentNotice = pgTable(
  'respondent_notice',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseRespondentId: uuid('case_respondent_id')
      .notNull()
      .references(() => caseRespondent.id, { onDelete: 'restrict' }),
    seqNo: integer('seq_no').notNull(), // 1, 2, 3 …
    correspondenceId: uuid('correspondence_id'),

    /** The despatch date the officer confirmed. Timers run from here. */
    sentAt: timestamp('sent_at', { withTimezone: true }),
    serviceMode: serviceModeEnum('service_mode'),
    /** The scanned registered-post acknowledgement card. */
    serviceProofDocumentId: uuid('service_proof_document_id'),

    replyDueAt: date('reply_due_at'),
    replyReceivedAt: timestamp('reply_received_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('respondent_notice_uq').on(t.caseRespondentId, t.seqNo)],
);

/**
 * Dates are events, not columns. Append-only, so adding a register column later is a view
 * change rather than a migration.
 */
export const caseMilestone = pgTable(
  'case_milestone',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    milestone: milestoneEnum('milestone').notNull(),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    /**
     * Mandatory. Anything other than `recorded` is footnoted in every export and printed
     * case file — which is what stops a reconstructed backlog date from becoming
     * indistinguishable from a recorded fact in an RTI reply or a writ petition.
     */
    dateSource: dateSourceEnum('date_source').notNull(),
    caseRespondentId: uuid('case_respondent_id').references(() => caseRespondent.id, {
      onDelete: 'set null',
    }),
    seqNo: integer('seq_no'),
    refTable: text('ref_table'),
    refId: uuid('ref_id'),
    note: text('note'),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
    recordedBy: uuid('recorded_by').references(() => appUser.id, { onDelete: 'set null' }),
  },
  (t) => [index('case_milestone_case_ix').on(t.councilId, t.caseFileId, t.occurredAt)],
);

export const caseStateHistory = pgTable(
  'case_state_history',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    fromState: caseStateEnum('from_state'),
    toState: caseStateEnum('to_state').notNull(),
    event: text('event').notNull(),
    reason: text('reason'),
    actorUserId: uuid('actor_user_id').references(() => appUser.id, { onDelete: 'set null' }),
    /** True when the engine raised it (ALL_RESPONDENTS_RESOLVED), not a person. */
    isSystem: boolean('is_system').notNull().default(false),
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('case_state_history_case_ix').on(t.councilId, t.caseFileId, t.occurredAt)],
);

/**
 * Every touch — email, phone call, WhatsApp, post. The satisfaction primitive for
 * follow-ups: an inbound contact from the waiting party closes the timer.
 *
 * Phone calls matter here. "Telephoned twice, no answer" is half of an ex parte
 * justification, and it is invisible unless it is written down.
 */
export const contactEvent = pgTable(
  'contact_event',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    partyId: uuid('party_id').references(() => party.id, { onDelete: 'set null' }),
    channel: contactChannelEnum('channel').notNull(),
    direction: contactDirectionEnum('direction').notNull(),
    purpose: text('purpose'),
    summary: text('summary').notNull(),
    outcome: text('outcome'), // 'no_answer' | 'spoke' | 'left_message' | …
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
    recordedBy: uuid('recorded_by').references(() => appUser.id, { onDelete: 'set null' }),
  },
  (t) => [index('contact_event_case_ix').on(t.councilId, t.caseFileId, t.occurredAt)],
);

/** Append-only revisions. Nothing is edited in place on a legal record. */
export const caseNote = pgTable(
  'case_note',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    councilId: uuid('council_id')
      .notNull()
      .references(() => council.id, { onDelete: 'restrict' }),
    caseFileId: uuid('case_file_id')
      .notNull()
      .references(() => caseFile.id, { onDelete: 'restrict' }),
    body: text('body').notNull(),
    /** Points at the note this one revises; the UI shows an "Amended" chip with who and why. */
    supersedesNoteId: uuid('supersedes_note_id'),
    amendmentReason: text('amendment_reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid('created_by').references(() => appUser.id, { onDelete: 'set null' }),
  },
  (t) => [index('case_note_case_ix').on(t.councilId, t.caseFileId, t.createdAt)],
);
